### ISSUE TITLE
Please update to version 1.0.1

### ISSUE THREAD

**Issue by shaula** [icedream/docker-guetzli#1]
Hello, thanks for your work. Your image is the best as it has got a decent size.

[Guetzli Version 1.0.1](https://github.com/google/guetzli/releases) was already released and contains many bug fixes (avoids crashes and gives more meaningful error messages).

Could you please update?

**Comment by icedream** [comment]
Thank you very much for giving notice about the new release, I have missed it! I'm on it now and fixing some linking errors related to the update and I'll let you know once the image has been updated on Docker Hub. 😄

**Comment by icedream** [comment]
The update is now published to Docker Hub under the tags `latest`, `1` and `1.0.1`. Once again thanks for the notice and let me know if there's any issues with the image!
